config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :discussions do
    resources :comments, only: [:create]
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :my_campaigns, only: [:index]
  resources :nearby_campaigns, only: [:index]

  resources :campaigns do
    resources :pledges, only: [:create, :destroy]
    resources :publishings, only: [:create]
    resources :comments, only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  root "campaigns#index"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user
  before_action :find_pledge

  def new
    @pledge = current_user.pledges.find(params[:pledge_id])
  end

  def create
    stripe_customer = Stripe::Customer.create(
                          description: "Customer for #{current_user.email}",
                          source: params[:stripe_token]
                        )

      current_user.stripe_customer_id       = stripe_customer.id
      current_user.stripe_last_4            = stripe_customer.sources.data[0].last4
      current_user.stripe_card_type         = stripe_customer.sources.data[0].brand
      current_user.stripe_card_expiry_month = stripe_customer.sources.data[0].exp_month
      current_user.stripe_card_expiry_year  = stripe_customer.sources.data[0].exp_year

      current_user.save

      charge = Stripe::Charge.create(
                  amount:      @pledge.amount * 100,
                  currency:    "cad",
                  customer:    current_user.stripe_customer_id,
                  description: "Charge for pledge id: #{@pledge.id}"
                )

      @pledge.stripe_txn_id = charge.id
      @pledge.save

      redirect_to @pledge.campaign, notice: "Thanks for completing the payment"
  end

  private

  def find_pledge
    @pledge = current_user.pledges.find params[:pledge_id]
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<h1>Make a Payment</h1>

<div class="alert alert-danger hide" id="stripe-error-message"></div>

<%= form_tag "", id: "payment-form" do %>
  <div class="form-group">
    <%= label_tag :card_number %>
    <%= text_field_tag :card_number, "", class: "form-control", data: {stripe: "number"} %>
  </div>
  <div class="form-group">
    <%= label_tag :cvc %>
    <%= text_field_tag :cvc, "", class: "form-control", data: {stripe: "cvc"} %>
  </div>
  <div class="form-group">
    <%= label_tag :card_expiry %>
    <%= select_month Date.today, {add_month_numbers: true}, {class: "form-control", data: {stripe: "exp-month"}} %>
    <%= select_year Date.today, {start_year: Time.now.year, end_year: Time.now.year + 10}, {class: "form-control", data: {stripe: "exp-year"}} %>
  </div>

  <%= submit_tag "Make the Payment", class: "btn btn-primary" %>
<% end %>

<%= form_tag pledge_payments_path(@pledge), id: "server-form" do %>
  <%= hidden_field_tag :stripe_token %>
<% end %>