config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :discussions do
    resources :comments, only: [:create]
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :my_campaigns, only: [:index]
  resources :nearby_campaigns, only: [:index]

  resources :campaigns do
    resources :pledges, only: [:create, :destroy]
    resources :publishings, only: [:create]
    resources :comments, only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  root "campaigns#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  # This integrates FriendlyId within our model. We're using the 'name' to generate the slug
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  validates :name, presence: true, uniqueness: true
  validates :goal, presence: true,
               numericality: {greater_than_or_equal_to: 10}

  belongs_to :user
  has_many :pledges, dependent: :destroy

  has_many :rewards, dependent: :destroy

  has_many :comments, as: :commentable

  geocoded_by :address   # can also be an IP address. Would use an IP address beacause we dont need to ask the users permission. The IP address is sent automatically with each request

  after_validation :geocode          # auto-fetch coordinates

  include AASM

  # setting the whiny_transitions: false option makes it so that it won't throw an exception when an invalid transition happen
  aasm whiney_transtions: false do
    state :draft, initial: true
    state :published
    state :unfunded
    state :funded
    state :canceled

    event :publish do
      transitions from: :draft, to: :published
    end

    event :cancel do
      transitions from: [:draft, :published, :funded], to: :canceled
    end

    event :fund do
      transitions from: :published, to: :funded
    end

    event :unfund do
      transitions from: :published, to: :unfunded
    end
  end

  def published
    where(aasm_state: :published)
  end
  # this enables us to create associated rewards models at the same time we're
  # creating the campaign model.
  # reject_if: :all_blank means that if the user leaves all the fields for the
  #                       reward empty, it will be ignored and not passed to the
  #                       validation
  # allow_destroy: true   means that if you pass in a special attributes _destroy
  #                       with value `true` as part of the `reward` params it
  #                       will delete the reward record all together.
  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true # this means that if they have left the fields blank it will just ignore it. This means that if they only have two rewards you don't have errors


  # This is CarrierWave config:
  # :image is the field in the database that will store the image name
  # ImageUploader is the uploader class we created in /app/uploaders/image_uploader.rb
  mount_uploader :image, ImageUploader

  # def to_param
  #   # for `to_param` to work there must be and id with non-numerical character
  #   # right after. It's good to call a method like `parameterize` which makes it
  #   # url friendly. For instance, `parameterize` replaces spaces with `-`s
  #   "#{id}-#{name}".parameterize
  # end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_action :find_campaign, only: [:show, :edit, :update]
  before_action :authenticate_user, only: [:destroy]

  REWARD_COUNT = 3

  def new
    @campaign = Campaign.new
    REWARD_COUNT.times { @campaign.rewards.build }
  end

  def create
    service = Campaigns::CreateCampaign.new(user: current_user, params: campaign_params)
    if service.call
      flash[:notice] = "Campaign created"
      redirect_to campaign_path(service.campaign)
    else
      @campaign = service.campaign
      build_associated_rewards
      flash[:alert] = "Campaign not created"
      render :new
    end
  end

  def show
    # find_by_id will not throw an error if it can't find anything. It will return
    # a nil
    @comment = Comment.new
    @pledge  = Pledge.new
  end


  def index
    @campaigns = Campaign.order("created_at ASC").published
  end

  def edit
    build_associated_rewards
  end

  def update
    # we need to force the slug to be nil before updating it in order to have
    # FriendlyId generate a new slug for us. We're using `history` option with
    # FriendlyId so old urls will still work.
    @campaign.slug = nil
    if @campaign.update campaign_params
      redirect_to campaign_path(@campaign), notice: "Campaign updated!"
    else
      flash[:alert] = "Campaign not updated"
      render :edit
    end
  end

  def destroy
    user_campaign.destroy
    redirect_to campaigns_path, notice: "Campaign deleted!"
  end

  private

  def build_associated_rewards
    number_to_build = REWARD_COUNT - @campaign.rewards.size
    number_to_build.times { @campaign.rewards.build }
  end

  def campaign_params
    # params.require(:campaign).permit(:name, :goal, :description, :end_date, :image, {rewards_attributes: [:amount, :title, :id, :_destroy]})

    params.require(:campaign).permit(:name, :goal, :description, :end_date, :image, {rewards_attributes: [:amount, :title, :id, :_destroy]})
  end

  def find_campaign
    @campaign = Campaign.friendly.find(params[:id]).decorate
  end

  def user_campaign
    @user_campaign ||= current_user.campaigns.friendly.find(params[:id])
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def markers(campaigns)
    Gmaps4rails.build_markers(campaigns) do |campaign, marker|
      marker.lat campaign.latitude
      marker.lng campaign.longitude
      campaign_link = link_to campaign.name, campaign_path(campaign)
      marker.infowindow campaign.title
    end
  end

end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>
  <%= f.input :name, label: "Campaign Name", input_html: {class: "small_field"}%>
  <%= f.input :description %>
  <%= f.input :goal, as: :string %> <%# this is to tell it to use just a textbox rather than the usual number field. %>
  <%= f.input :end_date %>
  <%# f.file_field :image  %>
  <%= f.input :image %>
  <div id="rewards">
    <%= f.simple_fields_for :rewards do |r| %>
      <%= render "reward_fields", f: r %>
    <% end %>
    <div class="links">
      <%= link_to_add_association "Add Reward", f, :rewards %>
    </div>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/campaigns/_reward_fields.html.erb
<div class="nested-fields">
  <%= f.input :title %>
  <%= f.input :amount, as: :string %>
  <%= link_to_remove_association "remove reward", f %>
  <hr>
</div>

app/views/campaigns/edit.html.erb
<h1>Edit Campaign</h1>
<%= render "form" %>

app/views/campaigns/index.html.erb
<h1>Recent Campaigns</h1>

<h2>All Campaigns</h2>
<% @campaigns.each do |c| %>
  <div class="well">
    <%= link_to c.name.upcase , c %>
  </div>
<% end %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render "form" %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.name %></h1>

<p><%= @campaign.description %></p>

<p>Goal: <%= @campaign.goal %></p>

<p>End Date: <%= @campaign.end_date %></p>

<%= @campaign.state_label %>

<%= @campaign.publish_button %>

<% if @campaign.image %>
  <%= image_tag @campaign.image.url(:large) %>
<% end %>

<% if @campaign.longitude && @campaign.latitude %>
  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
  <script>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @campaign.latitude %>,
        "lng": <%= @campaign.longitude %>,
        // "picture": {
        //   "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        //   "width":  32,
        //   "height": 32
        // },
        "infowindow": "hello Codecore!"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });
  </script>
<% end %>

<%= link_to "Edit", edit_campaign_path(@campaign), class: "btn btn-info" %>

<%= link_to "Destroy", @campaign,
            method: :delete,
            data: {confirm: "Are you sure?"},
            class: "btn btn-danger"  %>

<h2>Rewards</h2>
<% @campaign.rewards.each do |reward| %>
  <div class="well col-md-3">
    <h3><%= reward.title %></h3>
    <p><%= number_to_currency(reward.amount) %></p>
  </div>
<% end %>
<hr>

<h2>Pledge</h2>
<%= simple_form_for [@campaign, @pledge] do |f| %>
  <%= f.input :amount %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<hr>

<%= simple_form_for [@campaign, @comment] do |f| %>
  <%= f.input :body %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<% @campaign.comments.each do |com| %>
  <div class="well">
   <%= com.body %>
  </div>
<% end %>