config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :discussions do
    resources :comments, only: [:create]
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :my_campaigns, only: [:index]
  resources :nearby_campaigns, only: [:index]

  resources :campaigns do
    resources :pledges, only: [:create, :destroy]
    resources :publishings, only: [:create]
    resources :comments, only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  root "campaigns#index"

end

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
|
<% if user_logged_in? %>
  Hello <%= current_user.full_name %>
  <%= link_to "My Campaigns", my_campaigns_path %>
  <%= link_to "Sign Out", sessions_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_path %>
  <%= link_to "Sign Up", new_user_path %>
<% end %>
|
<%= link_to "New Campaign", new_campaign_path %>
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif alert  %>
  <div class="alert alert-danger">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Fund.sy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <meta name="stripe-publishable-key" content="<%= Rails.application.secrets.stripe_publishable_key %>"
</head>
  </head>
  <body>
    <div class="container">
      <%= render "/layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>